feature/9-registration-page-mobile
d-lama/d-lama-webapp pull request #23
Opened 2023-03-29 19:00 UTC by vonwareb

- created Registration.tsx and Registration.css
- added necessary inputfields
- added "Register" button

closes #9

2023-04-13 07:39 UTC, schazadm requested changes
overall formatting the code would be good for readability
otherwise already very well 👍

2023-04-13 07:39 UTC, schazadm commented on src/components/forms/Button.css
it's alright to remove or not add .css files if not used

2023-04-13 07:39 UTC, schazadm commented on src/pages/Registration.css
here the same as Button.css

2023-04-13 07:39 UTC, schazadm commented on src/components/forms/Input.css
same as Button.css

2023-04-13 07:39 UTC, schazadm commented on src/pages/Login.tsx
> +                            </IonButton>*/}
remove dead code

2023-04-13 07:39 UTC, schazadm commented on src/pages/Registration.tsx
looks pretty good 😁👍

2023-04-14 14:05 UTC, vonwareb commented on src/pages/Registration.css
removed Registration.css

2023-04-14 14:05 UTC, vonwareb commented on src/components/forms/Input.css
removed Input.css

2023-04-14 14:07 UTC, vonwareb commented on src/App.tsx
Done

2023-04-14 14:08 UTC, vonwareb commented on src/pages/Login.tsx
> +                            </IonButton>*/}
Done

2023-04-14 14:09 UTC, vonwareb commented on src/pages/Registration.tsx
Thank you for the feedback :-)

2023-04-25 16:18 UTC, merged

2023-05-01 09:36 UTC, Yingrjimsch commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/d-lama/d-lama-webapp/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-05-02 07:53 UTC, Yingrjimsch commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/d-lama/d-lama-webapp/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: